language: objective-c
osx_image: beta-xcode6.3

before_install:
- gem install xcpretty --no-rdoc --no-ri --no-document --quiet

script:
- set -o pipefail
- xcodebuild -workspace TypetalkKit.xcworkspace -scheme TypetalkKit-OSX build -sdk macosx10.10     ONLY_ACTIVE_ARCH=YES | xcpretty -c
- xcodebuild -workspace TypetalkKit.xcworkspace -scheme TypetalkKit-iOS test  -sdk iphonesimulator ONLY_ACTIVE_ARCH=YES | xcpretty -c
- pod lib lint --quick
