language: objective-c
osx_image: xcode611

before_install:
- gem install xcpretty --no-rdoc --no-ri --no-document --quiet
- gem install cocoapods --pre
- pod --version
- pod setup --silent
- pod repo update

script:
- set -o pipefail
- xcodebuild -workspace TypetalkKit.xcworkspace -scheme TypetalkKit -destination 'platform=iOS Simulator,OS=8.1,name=iPhone 6' test | xcpretty -c
- pod lib lint --quick
